### ISSUE TITLE
Add missing type annotations

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/Ninia#14]
Whenever a type annotation is missing or marked as `any`, we should endeavor to specify a type or a union type (e.g. `Py_Int | Py_Long`), which are supported by TypeScript.

Example: The stack is typed as `any[]`, but all types are subtypes of `Py_Object`, I think. It should really be `Py_Object[]`.

Type annotations will tighten up the code, root out any invalid type assumptions we have in the code, and make code easier to read.

**Comment by perimosocordiae** [comment]
Note: Function objects are also pushed on the stack, and as of now we represent them as JS function objects.

**Comment by jvilk** [comment]
Then we can do `(Function | Py_Object)[]`. I'd like to know if we have any assurances from the compiler regarding if functions can flow to `add` or something.

**Comment by jvilk** [comment]
(I assume all bets are off since it's Python)

**Comment by jvilk** [comment]
Fixed, and `noImplicitAny` turned on.
