### ISSUE TITLE
Finish implementation of generator objects

### ISSUE THREAD

**Issue by perimosocordiae** [plasma-umass/Ninia#38]
As of e30f53e96b61064584f4fc53c0d7c6e06e6ef2f0, the two failing tests which exercised generator objects are now skipped, which means that Travis is now reporting a passing build (yay). I'm creating this issue to remind us that generators are still broken.

Rough roadmap:

 - [x] Convert the `next(): IPy_Object` method of the `Iterator` interface to `$__next__`, which should be a `Py_AsyncNativeFuncObject`. We probably want to keep around the convenient, non-async versions around as well, like we do with other combination native/python methods.
 - [x] Call `$__next__` from the FOR_ITER opcode.
 - [x] Add an implementation for the YIELD_VALUE opcode to `src/optable.ts`. (Will probably look similar to the RETURN_VALUE opcode.)
 - [x] Figure out how to resume and suspend execution from the off-stack frame stored in the generator object. This gets resumed by `$__next__` and suspended at each YIELD_VALUE.
 - [x] Handle the special `StopIteration` exception, which signals that a generator has been exhausted.

**Comment by jvilk** [comment]
Muhammad will work on this as his final GSoC assignment, since he's completed everything else we've thrown at him. :)

**Comment by jvilk** [comment]
Muhammad has tackled all of these things, and they seem to work! (Of course, if you find a bug, create a test & file an issue.)
