### ISSUE TITLE
Handling circular dependencies

### ISSUE THREAD

**Issue by geremih** [plasma-umass/Ninia#7]
I am interested in taking part in GSoC 2015 and was looking at completing the implementation of divmod. The implementation of divmod would require `Py_Int.divmod()` to return a `Py_Tuple`, which would look something like https://github.com/geremih/Ninia/commit/9e07809287824d8f8f91ae4470e4989f161c0489. However, this will lead to a circular dependency as  collections.ts depends on integer.ts. I couldn't find a canonical way to handle this. Can anyone suggest something?

**Comment by perimosocordiae** [comment]
Yep, this circular dependency issue comes up from time to time, and unfortunately it's not easy to fix the "right way". It is possible to work around by deferring the import until after the necessary modules are loaded, I believe. @jvilk, how did we do this for Doppio?

Another solution is to make sure all of functions that call `divmod` remember to wrap the result in a `Py_Tuple`.

**Comment by jvilk** [comment]
Hey @geremih! This is a great question, and can get really annoying. We didn't solve the issue in Doppio, since we currently have no circular dependencies. We carefully crafted import statements so it doesn't happen.

I'd like to eventually transition to TypeScript internal modules, which do not have the circular dependency issue. I'll take a look at your code change to see if there's a way we can hack around this.

**Comment by jvilk** [comment]
Yeah, I think the best way is to defer `require` in some manner.

**Comment by geremih** [comment]
Is it possible to have a deferred `require` for this case?
```typescript
//a.ts
import B = require('./b');
export class A {
  func(): B {
    return new B();
  }
}
//b.ts
import A = require('./a');
export class B {
  func(): A {
    return new A();
  }
}
```
This case is analogous to the case of all numerics having  `__divmod__()` which returns a `Py_Tuple`, and `Py_Tuple` returning `Py_Int` for `len()`.
If it is possible to solve this case with a deferred `require`, then that should solve most of the cases?

**Comment by jvilk** [comment]
Yeah, you can defer the require... but you'll have to not use TypeScript's `import`.

You can probably do:

```
//a.ts
import B = require('./b');
export class A {
  func(): B {
    return new B();
  }
}
//b.ts
import _A = require('./a');
var A: typeof _A;
export class B {
  func(): _A {
    if (!A) A = require('./a');
    return new A();
  }
}
```

I know it's ugly.

**Comment by jvilk** [comment]
I just merged all of the numeric types into a single file, since widening operations means that we'll need to cross-ref them anyway.

The file seems rather large, but my proposal in #13 will shrink it considerably.

**Comment by perimosocordiae** [comment]
I'm closing this issue, as the original problem has been resolved.
